#!/bin/bash

blockMesh 

surfaceFeatureExtract 

snappyHexMesh -overwrite 

topoSet -dict system/createInletOutletSets.topoSetDict

createPatch -overwrite

decomposePar -force

foamJob -parallel -screen simpleFoam
